# Default values for atomic-reactor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: app
  # pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

app:
  replicaCount: 1
  terminationGracePeriodSeconds: 30
  ajAppMonitoring:
    enabled: false
    # environment: dev
    # name: atomic-reactor
    # slackmoji: rocket
  env: []
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 1Gi

  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  autoscaling:
    enabled: false
    # minReplicas: 1
    maxReplicas: 10
    metrics: []
      # - type: Resource
      #   resource:
      #     name: cpu
      #     target:
      #       type: Utilization
      #       averageUtilization: 80
    behavior: {}

readinessProbePath: "/health"

# Environment variable name passed to the app pointing at the mounted env file
envFileVar: APP_ENV_FILE

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

topologySpreadConstraint:
  enabled: false
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule

service:
  type: ClusterIP
  name: reactor
  port: 80
  containerPort: 8080

ingress:
  enabled: false
  #ingressClassName: alb
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  rules: []
  #  - host: atomic-reactor.example.com
  #    http:
  #      paths:
  #      - path: /
  #        pathType: Prefix
  #        backend:
  #          service:
  #            name: app
  #            port:
  #              number: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}

externalSecrets:
  env:
    enabled: false
    data: []
    # data:
    # - secretKey: env
    #   remoteRef:
    #     key: /path/to/env
    secretStoreRef: {}
    # secretStoreRef:
    #   name: aws-ssm
    #   kind: ClusterSecretStore
    refreshInterval: 2m
    dataFrom: []
    target:
      creationPolicy: Orphan
      deletionPolicy: Retain

  redis:
    enabled: false
    data: []
    # data:
    # - secretKey: redis.conf
    #   remoteRef:
    #     key: /path/redis.conf
    secretStoreRef: {}
    # secretStoreRef:
    #   name: aws-ssm
    #   kind: ClusterSecretStore
    refreshInterval: 2m
    dataFrom: []
    target:
      creationPolicy: Orphan
      deletionPolicy: Retain

redis:
  enabled: false
  #image.registry: public.ecr.aws/docker/library

  # Additional configuration (e.g. password)
  extraSecretRedisConfigs: redis-config

  useDeploymentWhenNonHA: true

  metrics:
    enabled: true
    exporter:
      extraExporterEnvSecrets:
        - redis-exporter

  serviceMonitor:
    enabled: true

  resources:
    requests:
      memory: 100Mi
    limits:
      memory: 200Mi

  redisConfig: |-
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    maxmemory-policy allkeys-lru
    save ""
