{{- if .Values.cronjobs.enabled -}}
{{- $top := . -}}
{{- range $cronjob := .Values.cronjobs.jobs -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "app.fullname" $top }}-{{ $cronjob.name }}
  labels:
    {{- include "app.labels" $top | nindent 4 }}
  namespace: {{ $top.Release.Namespace }}
spec:
  schedule: "{{ $cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- with $top.Values.cronjobs.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ include "app.serviceAccountName" $top }}
          restartPolicy: OnFailure
          securityContext:
            {{- toYaml $top.Values.podSecurityContext | nindent 12 }}
          {{- with $top.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: rake
            image: "{{ $top.Values.image.repository }}:{{ $top.Values.image.tag }}"
            imagePullPolicy: {{ $top.Values.image.pullPolicy }}
            command: ["/bin/bash"]
            args:
            - "-c"
            - "{{ $cronjob.task }}"
            resources:
              {{- toYaml $top.Values.cronjobs.resources | nindent 14 }}
            volumeMounts:
              - name: secrets
                mountPath: /app/config/k8s
              - name: credentials
                mountPath: /app/config/credentials
              {{- if $top.Values.persistence.enabled }}
              - name: shared
                mountPath: /shared
              {{- end }}
          volumes:
            - name: secrets
              secret:
                secretName: {{ $top.Values.configSecret }}
            - name: credentials
              secret:
                secretName: {{ $top.Values.credentialsSecret }}
            {{- if $top.Values.persistence.enabled }}
            - name: shared
              persistentVolumeClaim:
                claimName: {{ template "app.fullname" $top }}
            {{- end }}
---
{{- end }}
{{- end }}
