{{- if and ( .Capabilities.APIVersions.Has "external-secrets.io/v1" ) .Values.externalSecrets.env.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "atomic-reactor.fullname" . }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
spec:
  data:
    {{- toYaml .Values.externalSecrets.env.data | nindent 4 }}
  dataFrom:
    {{- toYaml .Values.externalSecrets.env.dataFrom | nindent 4 }}
  refreshInterval: {{ .Values.externalSecrets.env.refreshInterval }}
  secretStoreRef:
    {{- toYaml .Values.externalSecrets.env.secretStoreRef | nindent 4 }}
  target:
    {{- toYaml .Values.externalSecrets.env.target | nindent 4 }}
    name: atomic-reactor
{{- end }}
