{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "atomic-reactor.fullname" . }}
  labels:
    {{- include "atomic-reactor.labels" . | nindent 4 }}
  {{- if .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
    {{- include "atomic-reactor.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.scrapeInterval }}
{{- end }}
